### PR TITLE
EditorConfig

### PR DESCRIPTION
**Pull request by shoushou1106**
Add .editorconfig that let IDE follows CodingStandards.cs

### CODE REVIEW

**Comment by shoushou1106** [comment]
If [reformat](https://github.com/wannkunstbeikor/FrostyToolsuite/pull/23/commits/6fbc06042afa8007b07bf1743f684fbbd439c258) is inappropriate please let me know and I will roll it back(and idk why it cause conflicts)
namespace config is error now

**Comment by wannkunstbeikor** [comment]
u need to create a branch based on my master branch, so it doesnt conflict with it, else i cant merge it.

for this u need to add my repo as a remote and then just create a new branch based on my master branch
```
git remote add <some name> https://github.com/wannkunstbeikor/FrostyToolsuite.git
git fetch <some name>
git branch <branch name> <some name>/master
```

**Comment by wannkunstbeikor** [comment]
i cant merge it like this

**Comment by wannkunstbeikor** [comment]
just create one through github and select my master branch as the source

**Comment by wannkunstbeikor** [comment]
also im not a fan of the space after a method name and before the ()

**Comment by shoushou1106** [comment]
@wannkunstbeikor can you merge this now? then i will make a new branch for auto reformat

**Comment by wannkunstbeikor** [comment]
Some small changes to the config would be great.

`public void Test() instead of public void Test ()`

```
switch ()
{
    case :
    {
    }
}
```

instead of 

```
switch ()
{
    case :
        {
        }
}
```

and
```
new Class
{
    Variable = 1
}
```
instead of `new Class { Variable = 1 }`

**Comment by shoushou1106** [comment]
oh sorry i forgot that

**Comment by shoushou1106** [comment]
> ```
> new Class
> {
>     Variable = 1
> }
> ```
> 
> instead of `new Class { Variable = 1 }`

sorry idk how to do that

**Comment by wannkunstbeikor** [comment]
its okay then, if we figure it out we can add it later, just commit the changes and i will merge it

**Comment by wannkunstbeikor** [comment]
i think u just need to do csharp_new_line_before_open_brace = all

**Comment by shoushou1106** [comment]
> its okay then, if we figure it out we can add it later, just commit the changes and i will merge it

ok you can merge it now
btw can you reformat by yourself and commit it
图片

**Comment by shoushou1106** [comment]
> i think u just need to do csharp_new_line_before_open_brace = all

i have already do that

**Comment by wannkunstbeikor** [comment]
also why did u change the versions of some of the editor packages

**Comment by shoushou1106** [comment]
> also why did u change the versions of some of the editor packages

idk, i change it back now

**Comment by wannkunstbeikor** [comment]
okay thanks a lot

**Pull request merged**
